# This is a basic workflow to help you get started with Actions
name: CI-ECR-BASE
on:
  workflow_call:
    inputs:
      WF_SERVICE_NAME:
        type: string
        required: true
      WF_ENV_TYPE:
        type: string
        required: true
      WF_NODE_VERSION:
        type: string
        required: true
    secrets:
      WF_NPM_TOKEN:
        required: true
      WF_NPM_USER:
        required: true
      WF_GITHUB_TOKEN:
        required: true
      WF_AWS_ACCESS_KEY_ID:
        required: true
      WF_AWS_SECRET_ACCESS_KEY:
        required: true
      WF_AWS_REGION:
        required: true
    outputs:
      servicename:
        description: "The service name"
        value: ${{ jobs.setup.outputs.servicename }}
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    name: preparing
    runs-on: ubuntu-latest
    environment: production
    continue-on-error: false
    outputs:
      servicename: ${{ steps.service-name.outputs.servicename }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.WF_NODE_VERSION }}
          cache: 'yarn'
          registry-url: ${{secrets.WF_REGISTRY}}
      
      - name: Configure AWS credentials without role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.WF_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.WF_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.WF_AWS_REGION }}
      
      - name: Creating .env from aws parameter store
        uses: almerindo/action-env-from-aws-ssm@v1.2.0
        with:
          output: ./environments/.env
          ssm-path: '/${{ inputs.WF_ENV_TYPE }}/${{ inputs.WF_SERVICE_NAME }}'
          format: dotenv
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WF_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.WF_AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: getting last commit and hash
        id: git-hash
        run: |
          echo 'COMMIT-HASH --> ${{ github.sha }}'
          git pull origin main
          hash=$(git rev-parse HEAD)
          echo 'NEW HASH $hash'
          
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: '${{inputs.WF_SERVICE_NAME}}_${{inputs.WF_ENV_TYPE}}_repo'
          IMAGE_TAG: latest
          VERSION_TAG: ${{ github.sha }}
          SERVICE_NAME: ${{ inputs.WF_SERVICE_NAME }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          echo "registry=http://registry.npmjs.org/" > .npmrc && echo "${{ secrets.WF_NPM_USER }}:registry=https://npm.pkg.github.com" >> .npmrc && echo "//npm.pkg.github.com/:_authToken=${{ secrets.WF_NPM_TOKEN }}" >> .npmrc
          docker build --build-arg SERVICE_NAME=$SERVICE_NAME -t $ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REPOSITORY:$VERSION_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REPOSITORY:$VERSION_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG"
          echo "COMMIT-HASH --> $VERSION_TAG"
          hash=$(git rev-parse HEAD)
          echo $hash
           
      - name: Setting service name outputs
        id: service-name
        run: |
          export SERVICE_NAME=${{inputs.WF_SERVICE_NAME}}
          echo "::set-output name=servicename::$SERVICE_NAME"
