# This is a basic workflow to help you get started with Actions
name: CI-LOCAL
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    name: preparing
    runs-on: ubuntu-latest
    continue-on-error: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: 'yarn'
      - name: install packages using yarn.lock
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WF_NPM_TOKEN }} 
        run: |
          yarn --frozen-lockfile

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.WF_NPM_TOKEN }} 
          GITHUB_TOKEN: ${{ secrets.WF_GITHUB_TOKEN }}
        run: |
          yarn semantic-release