name: Remove uploaded preview in S3.

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      S3_BUCKET_NAME:
        required: true

jobs:
  clear_s3_preview:
    name: Clear S3 build preview
    runs-on: ubuntu-latest
    environment:
      name: stage

    env:
        PREVIEW_PREFIX: preview-pr-${{ github.event.pull_request.number }}

    steps:
      - name: Remove preview folder from S3
        run: |
          aws s3 rm "s3://${{ secrets.S3_BUCKET_NAME }}/${{ env.PREVIEW_PREFIX }}" --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}